import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => {
        let clipboard = '#00ff00'
        Object.defineProperty(navigator, 'clipboard', { configurable: true, value: {
            readText: async () => clipboard,
            writeText: async (text: string) => { clipboard = text },
        } })
    })
})

test('a shared value loads directly, survives reload, and takes precedence over the clipboard', async ({ page }) => {
    const value = '--brand: oklch(72% 0.09 310 / 25%);'
    const path = '/' + encodeURIComponent(value)
    const response = await page.goto(path)
    expect(response?.ok()).toBe(true)
    await expect(page.getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue(value)
    await expect(page.getByText('Reading from clipboard...')).toHaveCount(0)
    await expect(page.getByText('brand', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue(value)
    expect(new URL(page.url()).pathname).toBe(path)
    await page.getByRole('button', { name: 'Copy share link' }).click()
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(page.url())
})

test('edits update the address immediately and Back/Forward restore complete band values', async ({ page }) => {
    await page.goto('/%23ff0000')
    const input = page.getByRole('textbox', { name: 'Color value', exact: true })
    await input.fill('rgb(1, 2, 3)')
    await input.press('Enter')
    const firstEdit = page.url()
    expect(new URL(firstEdit).pathname).toBe('/' + encodeURIComponent('rgb(1, 2, 3)'))
    await input.fill('oklch(72% 0.09 310 / 25%)')
    await input.press('Enter')
    const secondEdit = page.url()
    await page.goBack()
    await expect(input).toHaveValue('rgb(1, 2, 3)')
    await expect(page).toHaveURL(firstEdit)
    await page.goBack()
    await expect(input).toHaveValue('#ff0000')
    await page.goForward()
    await expect(input).toHaveValue('rgb(1, 2, 3)')
    await page.goForward()
    await expect(input).toHaveValue('oklch(72% 0.09 310 / 25%)')
    await expect(page).toHaveURL(secondEdit)
})

test('a burst of typing creates one history entry and preserves keyboard focus', async ({ page }) => {
    await page.goto('/%23ff0000')
    const input = page.getByRole('textbox', { name: 'Color value', exact: true })
    await input.fill('')
    await input.pressSequentially('#abcdef', { delay: 30 })
    await expect(input).toBeFocused()
    await expect(input).toHaveValue('#abcdef')
    expect(new URL(page.url()).pathname).toBe('/%23abcdef')
    await page.goBack()
    await expect(input).toHaveValue('#ff0000')
    await page.goForward()
    await expect(input).toHaveValue('#abcdef')
})

test('multiple bands, splitting, add/reset, and photo navigation retain shareable history', async ({ page }) => {
    const inputs = ['#ff000080', 'oklch(72% 0.09 310 / 25%)', '--brand: hsl(240 100% 50%);']
    const path = '/' + inputs.map(encodeURIComponent).join('/')
    await page.goto(path)
    const bands = page.getByTestId('color-band')
    await expect(bands).toHaveCount(3)
    for (let index = 0; index < inputs.length; index++) await expect(bands.nth(index).getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue(inputs[index])
    await page.reload()
    await expect(bands).toHaveCount(3)
    await bands.first().getByRole('textbox', { name: 'Color value', exact: true }).fill('#fff #000')
    await expect(bands).toHaveCount(4)
    const splitUrl = page.url()
    await page.getByRole('button', { name: 'Add empty panel' }).click()
    await expect(bands).toHaveCount(5)
    await page.getByRole('button', { name: 'Reset to single panel' }).click()
    await expect(bands).toHaveCount(1)
    await page.goBack()
    await expect(bands).toHaveCount(5)
    await page.goBack()
    await expect(bands).toHaveCount(4)
    await expect(page).toHaveURL(splitUrl)
    await page.getByRole('link', { name: 'Photo picker', exact: true }).click()
    await expect(page).toHaveURL(/\/photo$/)
    await page.goBack()
    await expect(page).toHaveURL(splitUrl)
    await expect(bands).toHaveCount(4)
    await page.reload()
    await expect(bands).toHaveCount(4)
})

test('invalid and empty input can be shared without displaying fabricated conversions', async ({ page }) => {
    await page.goto('/%23ff0000')
    await page.getByRole('textbox', { name: 'Color value', exact: true }).fill('rgb(1px, 2, 3)')
    const invalidUrl = page.url()
    await page.reload()
    await expect(page.getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue('rgb(1px, 2, 3)')
    await expect(page.getByTestId('color-band').getByRole('alert')).toContainText('No supported color found')
    await expect(page).toHaveURL(invalidUrl)
    await page.getByRole('textbox', { name: 'Color value', exact: true }).fill('photo')
    await page.reload()
    await expect(page.getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue('photo')
    await expect(page.locator('.photo-stage')).toHaveCount(0)
    await page.getByRole('textbox', { name: 'Color value', exact: true }).fill('')
    await page.reload()
    await expect(page.getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue('')
    await expect(page.getByText('Enter a color to see its formats.')).toBeVisible()
})

test('pasting a clipboard palette creates a history entry for all of its bands', async ({ page }) => {
    await page.goto('/%23ff0000')
    await page.evaluate(() => navigator.clipboard.writeText('#abc #def'))
    await page.getByRole('button', { name: 'Paste colors from clipboard' }).click()
    await expect(page.getByTestId('color-band')).toHaveCount(2)
    expect(new URL(page.url()).pathname).toBe('/%23abc/%23def')
    await page.goBack()
    await expect(page.getByRole('textbox', { name: 'Color value', exact: true })).toHaveValue('#ff0000')
    await page.goForward()
    await expect(page.getByTestId('color-band')).toHaveCount(2)
})
